---
- name: "AWX CONFIGURE TASKS CREDENTIALS: Create credentials"
  awx.awx.credential:
    name: "{{ item.name }}"
    organization: "{{ item.owner.organization | default(omit) }}"
    team: "{{ item.owner.team | default(omit) }}"
    user: "{{ item.owner.user | default(omit) }}"
    state: present
    credential_type: "{{ item.credential_type }}"
    inputs:
      host: "{{ item.parameters.host | default(omit) }}"
      username: "{{ item.parameters.username | default(omit) }}"
      password: "{{ item.parameters.password | default(omit) }}"
      ssh_key_data: "{{ item.parameters.ssh_key_data | default(omit) }}"
      ssh_key_unlock: "{{ item.parameters.ssh_key_passphrase | default(omit) }}"
      vault_password: "{{ item.parameters.vault_password | default(omit) }}"
      vault_id: "{{ item.parameters.vault_id | default(omit) }}"
      become_method: "{{ item.parameters.become_method | default(omit) }}"
      become_password: "{{ item.parameters.become_password | default(omit) }}"
  loop: "{{ awx_config.credentials }}"
  when: awx_config.credentials | length > 0
